### ISSUE TITLE
Suggestion: Adjust blur intensity to match other Windows UI elements

### ISSUE THREAD

**Issue by myfrom** [AutoDarkMode/Windows-Auto-Night-Mode#139]
Currently the blurred sidebar effect doesn't match with the rest of the Acrylic effects in Windows UI. I think it would be great to have it consistent with the system, if possible.

<img src="https://user-images.githubusercontent.com/19410489/87851955-0935f180-c8fe-11ea-9807-051614e85a28.png" width="48%"><img src="https://user-images.githubusercontent.com/19410489/87851959-105cff80-c8fe-11ea-993e-1bcacefb3917.png" width="48%">

**Comment by Spiritreader** [comment]
There's currently an issue with the acrylic window effect for third party applications that disallows us from switching the background to acrylic without unacceptable impact on usability (see here for examples: https://github.com/Eugeny/terminus/issues/949)

This was supposed to be fixed in newer Windows builds but seems to still occur.

**Comment by Poopooracoocoo** [comment]
the navigation view's indicator is also not inline with WinUI's updates.

**Comment by Spiritreader** [comment]
FluentWPF needs an update for this. As soon as a new version is available, this should start to work. Expect it to be in a future release.

**Comment by Spiritreader** [comment]
FluentWPF has been updated to 0.10.2, which, compared to version 0.10.0 re-enables the acrylic blur when not moving the window.
Unfortunately it is not possible to enable acrylic blur while dragging the window due to a long standing windows bug.

Due to currently outstanding issues with transparency effects and windows 11, the fixed transparency effect is only available in Windows 10 for now.

![image](https://user-images.githubusercontent.com/18438899/136711848-1ee0291e-57f7-4091-9ba8-84f4bf26a89b.png)

Acrylic blur is now back starting with build 10.0.1.31
