### ISSUE TITLE
Suggestion: Microsoft Store UWP Variant release

### ISSUE THREAD

**Issue by VincentJoshuaET** [AutoDarkMode/Windows-Auto-Night-Mode#17]

**Comment by Armin2208** [comment]
I already tried to release my App to the Microsoft Store. This is even one of my dreams to have an App in am App-Store. Sadly, this isn't technically possible. I talked to a Microsoft Engineer and he confirmed that to me.

I created a developer account and uploaded the App to the store as private release. I tried some stuff out. No Chance for a theme switch in the app package.

**Comment by Armin2208** [comment]
With the new Microsoft Store supporting the delivery of .exe-files, Auto Dark Mode gets an Store Entry!
Currently the new Microsoft Store is only available on Windows 11, but with time it will also roll out to Windows 10.
It's not a UWP release, but it's a store release. So hey, it's kinda the middle of that!

We still can't provide an UWP which edits the registry and uses private APIs. That's why we close this issue now.

Will see you all at 5th october!

![image](https://user-images.githubusercontent.com/32982430/132128223-cd1d0385-f927-4f4c-a773-2197f73cd662.png)
