### ISSUE TITLE
Stuck on "Searching your location..."

### ISSUE THREAD

**Issue by VincentJoshuaET** [AutoDarkMode/Windows-Auto-Night-Mode#18]
**Describe the bug**
Another thing, the location status taskbar icon shows up for a few seconds but it disappears after a while.

**To Reproduce**
Press Use Location Service

**Environment:**
Windows 10 1903 18334.1
Auto-Night Mode 2.0

**Comment by Armin2208** [comment]
I can't reproduce this atm

**Comment by VincentJoshuaET** [comment]
Update: the location is detected successfully. But after it is detected, the mouse cursor changes into the spinning icon and the program closes.

**Comment by Dave247** [comment]
I had this happen to me upon first activating the option, but simply toggling the checkbox fixed it.

**Comment by Armin2208** [comment]
I designed location as followed:
- At every program start he looks for the user location, because people don't need and don't will start the program often. The background process handles theme switch + sunset & sunrise time adjustment. You can quickly switch the theme with jump list.
- The background process to adjust sunrise and sunset theme (it runs every weeks) uses the last saved location, so it will not again track the user to save battery and resources.

If it's irritating to always search for user location at program start, I can make it optional if you guys want this. For me the current way is good and I hadn't any issues yet.

**Comment by Dave247** [comment]
Actually you're right. Once set there really isn't much need to open the program again. For me, I was having a bit of a problem because I didn't realise that you couldn't set the accent colour for the taskbar when in light mode.

**Comment by Spiritreader** [comment]
ADM version X completely revamped the location update system. Please update and try again.
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/tag/10.0.0.26

Reopen this issue if still relevant.
