### ISSUE TITLE
Icon color in notification area not changing

### ISSUE THREAD

**Issue by ItzSreerag** [AutoDarkMode/Windows-Auto-Night-Mode#196]
When we change the theme to Dark or vice versa, some of the notification area icon colors don't change. It seems so bad when only one icon has a different color.

**Comment by Armin2208** [comment]
yes, you're right. Sadly it's the task of the app developers to insure a adapting tray icon.

**Comment by ItzSreerag** [comment]
No no.. Please see the screenshot and reply, please
![Screenshot_1](https://user-images.githubusercontent.com/73540930/104921455-56834080-59bf-11eb-9d0f-12f0e1c73452.png)

**Comment by Armin2208** [comment]
battery saver or connected to power?

**Comment by ItzSreerag** [comment]
The computer was connected to power. When the theme changes using the app, some of the system icons (not other app icons) change to white (because of dark mode) but some remain black (white mode) [Refer: Screenshot 1]. It looks so bad because it does not match the looks. Please fix it.

**Comment by Spiderlinker** [comment]
I have the same problem. When switching between light and dark mode, the Windows icons do not change. For example, the volume icon does not update until you change the volume. 
![grafik](https://user-images.githubusercontent.com/24277965/109038448-05582200-76cc-11eb-952c-11cf5e6b6209.png)

If you change the theme via the Windows settings, then the icons are also completely updated.
I also noticed that the font color of the subtitles in the Windows settings are also updated only after you have clicked on an option.

![grafik](https://user-images.githubusercontent.com/24277965/109039150-c1195180-76cc-11eb-94f5-13652db47df0.png)
![grafik](https://user-images.githubusercontent.com/24277965/109039201-d1313100-76cc-11eb-8fec-c1f28aaf8197.png)

App version: 3.0.1
Windows 10, 20H2

**Comment by ItzSreerag** [comment]
Okay.  Can you fix it if possible? Because different colors look odd, and
also black looks great.😎
Thanking you,

Yours sincerely,

Sreerag Rajesh
9074959750

**Comment by ikjadoon** [comment]
I'm having similar issues. For example, with the light theme enabled (should be **dark** icons on a *light* taskbar):

Monitor A:
![image](https://user-images.githubusercontent.com/3848795/111218811-9cb6e380-85ad-11eb-975a-508a5f65c5c5.png)

Monitor B:
![image](https://user-images.githubusercontent.com/3848795/111218828-a3455b00-85ad-11eb-96cd-e1325bd640ce.png)

Monitor C:
![image](https://user-images.githubusercontent.com/3848795/111218850-ab9d9600-85ad-11eb-8848-de32f843d435.png)

This is on a desktop with no power saver.

Auto Dark Mode 3.0.1
Windows 10 Professional x64 20H2 (19042.867)

**Comment by Spiritreader** [comment]
For some reason, when setting the registry key to switch the taskbar color, this does not propagate the update event to all elements.

This is more of a windows issue, however version x has made improvements that should at least mitigate / improve the situation until there is an established way to avoid this from happening. I noticed that putting a delay 

The issue with the windows settings unfortunately is also not fixable. This is again, unfortuantely Window's fault.

Some tweaks were done in version X, and I found a little improvement just now that makes it more reliable.
Since this varies system by system, setting the delay for switching taskbar colors is very important to individually configure.

For my system, it is 2850ms.
