### ISSUE TITLE
Discrepancy between geolocated times shown in the app and Windows Night light settings

### ISSUE THREAD

**Issue by bradenhilton** [AutoDarkMode/Windows-Auto-Night-Mode#255]
Apologies if this has been brought up before, I did look through some existing issues and couldn't find anything obvious.

I've noticed that the times shown in the app do not match those found in the Windows Night light settings.

My current understanding is that 3.0.1 uses the same service that Windows uses to set sun(set/rise) times, and that these times should therefore be identical.

Is it possible that this is caused by each service checking at different times? That is, checking later in a day should theoretically result in more accurate times.

I noticed if I disable location access, clear the location history, then re-enable location access, the times in the app often change, while the times in the Night light settings do not. I was thinking perhaps Windows checks for the times (whenever that is) and then caches the result but I'm honestly not sure.

You can see this in the following screenshot:
![suntimes](https://user-images.githubusercontent.com/23157013/132265013-92fa9651-ddaa-4c7b-97cf-3a00dc586874.png)
(Left: Windows Night light settings, Right: Auto Dark Mode)

Note that I took this screenshot after clearing location history and disabling/re-enabling location access. Before doing that, the times in Auto Dark Mode were Light: 06:28 and Dark: 19:48. The times in the Night light settings did not change.

I don't remember this happening when I was using 2.X a while ago, but I reinstalled it just to check and the same thing happens there, so I feel like this may be caused by a somewhat recent Windows update or something like that.

It's not a big deal, just thought I would mention it in the event that it could be fixed or worked around.

**Comment by Spiritreader** [comment]
Hello there!
Thank you for your contribution!

The behavior you described will partially change.

We are using Paul Shylter's https://stjarnhimlen.se/comp/sunriset.c method to determine sun times.
Slight discrepancies are to to be expected/intentional.
Please see this response by @jwfxpr.
https://github.com/microsoft/PowerToys/issues/1331#issuecomment-877337033.


The new beta-5 for version X which is under development uses a 24h timer to update the sun times.
This means that in the future, you'll most likely see slight changes in sunrise/sunset times every day.
