### ISSUE TITLE
Can't install in Windows11

### ISSUE THREAD

**Issue by Dec-35** [AutoDarkMode/Windows-Auto-Night-Mode#268]
**Description**
Can't install the program, apparently it can't acess its files. Even changing the installation path to another drive does not solve the issue. This happens with the microsoft store and the github versions.

**How to make the issue happen**
Double click the install.exe -> Choose language -> choose installation path -> get an error saying it can't access said path 

**Expected behaviour**
I wanted it to install

**Screenshots**
![image](https://user-images.githubusercontent.com/88966922/136096870-ad6a4af1-1d58-482c-966c-712f09a7a1e2.png)

**Commit Hash and Version**
10.0.0.26

**Additional context**
Just recently switched to windows 11

**Comment by Dec-35** [comment]
> Do you have administrator rights on your system?

I'm the only user of my laptop and am the admin. I tried running the stup.exe with admin rights but still the same issue. I can access the folder though...

**Comment by Spiritreader** [comment]
Okay interesting. 
What seems to be happening is that InnoSetup can't place the uninstaller correctly.
It is supposed to place it in the install directory, but for some reason it can't do that.

I wonder if this is due to a Windows policy or uninstaller configuration issue. I'm sadly not very knowledgeable when it comes to the installer, @Armin2208 will have to investigate this.

In the meantime, if you still want to use Auto Dark Mode, you can download the .zip file on the release page (AutoDarkModeX_10.0.0.26.zip) and extract it anywhere (but **NOT** into C:\Program Files). The app can run fully portable and is self-contained.

**Comment by Spiritreader** [comment]
Have you tried installing it without modifying the default path?

**Comment by hellodit** [comment]
Using default installation setting worked for me

**Comment by Spiritreader** [comment]
Installer has been reworked multiple times since then.

Please reopen if still an issue.
