### ISSUE TITLE
Some apps dont flip to Dark Mode

### ISSUE THREAD

**Issue by mstras** [AutoDarkMode/Windows-Auto-Night-Mode#283]
I am not sure if this is discussed somewhere else, but some apps don't flip to dark mode with the system. Slack and Whatsapp stay in whatever mode they started in.

**Comment by Spiritreader** [comment]
Apps generally have to support two features:
- respect the windows theme
- be able to switch automatically when the theme changes

Auto Dark Mode instructs windows to switch, and for all other apps it's their responsibility to follow the system theme.

For WhatsApp, you will have to reload the page/app when it switches to dark mode and the setting is on 'use system theme"

I am unfamiliar with slack theme switches.

Starting with version X, we also accept pull requests if people want to add functionality for custom components. These are for apps that do not support the first bullet point, but can be switched using a command. 

For all other apps, this is expected behavior.
