### ISSUE TITLE
Windows 11: Search menu

### ISSUE THREAD

**Issue by SonnyKlinger** [AutoDarkMode/Windows-Auto-Night-Mode#319]
I'm using the Sunset/Sunrise mode for switching the themes, and every First time I open the Search menu (Win+S) after the switch, the menu itself is on the right theme, but all the text is still on the old - Dark window with black text, or white text on a white window. After I close the Search window once, it shows up properly (until the next switch).

**Comment by Spiritreader** [comment]
This is an issue with Windows Theme switching that has existed since Windows 10. Text updates may only occur on refresh.
There is no way to refresh certain system components except to open them.
I suppose it will stay this way until Microsoft decides to fix this.
Unfortunately there is nothing for us to fix here, as it isn't related to Auto Dark Mode, but more to the APIs available.
