### ISSUE TITLE
Allow other accessibility color filters 

### ISSUE THREAD

**Issue by WindowsTablet** [AutoDarkMode/Windows-Auto-Night-Mode#360]
**Describe the enhancement or feature you'd like**

I would like to request the ability to use the other accessibility color filters, such as Grayscale Inverted (which I find more useful at night), or just send Win + Ctrl + C, while maintaining the user set color filter.

Please note that, if this is implemented, the Windows theme should stay in light mode for the inverted colors to work properly.

Thanks in advance.

**Comment by Spiritreader** [comment]
We've already been looking into this internally, and will very likely offer more configuration options.

If the windows theme should stay in light mode or not is something you would have to configure in Auto Dark Mode via the Apps tab.

**Comment by WindowsTablet** [comment]
Thanks.

**Comment by Spiritreader** [comment]
Since we maintain the color filter settings that are made by the user I consider this completed.

![image](https://user-images.githubusercontent.com/18438899/197641471-e84b8471-dd19-405b-ba80-0c0d625c3d59.png)

I don't think a UI is required for this, as there is a perfectly working one already in the Windows settings.
The way to configure it to select the setting whatever filter is desired. If it's not turned on at the moment, you may have to temporarily turn it on while changing the settings.
