### ISSUE TITLE
Allow Windows key (winkey) in keyboard shortcuts

### ISSUE THREAD

**Issue by tfiers** [AutoDarkMode/Windows-Auto-Night-Mode#418]
**Describe the enhancement or feature you'd like**

Allow Windows key (winkey) in keyboard shortcuts

**Describe alternatives you've considered**

A shortcut without the winkey (eg ctrl-shift-alt-L or -D, for Light/Dark).
Thing is, lotsa shortcuts are already used, in vscode eg.
Plus, semantically, "Windows" works well as switching color mode is an OS wide setting.

**Additional context**

Currently, pressing a key combination in the shortcut input boxes in the settings dialog drops the Win key if it is present in the combination. The other modifiers *are* retained.

Btw, a thousand thanks for this well made app.

**Comment by tfiers** [comment]
btw, a "toggle" command would be nice, so only one shortcut key is needed.
See the second part of this comment: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/5#issuecomment-496084208

**Comment by Spiritreader** [comment]
> btw, a "toggle" command would be nice, so only one shortcut key is needed.

Toggling is not possible because of how AutoDarkMode works. 
The switching logic runs a timer that applies dark and light switching operations at the appropriate point in time.
The "force light" and "force dark" options set the theme to light or dark respectively, and then *disable* the switching logic while still keeping it running.

What is on the radar would be something like "force theme until next sunrise/sunset", but no details on this yet.

We can't allow the Windows hotkey, as per default with the library we use, it isn't defined as a modifier key.
I have attempted to make it work with the library, but found it to be infeasible.

Thanks for you suggestions nonetheless!

**Comment by tfiers** [comment]
All clear, thanks for the prompt response and you folks' work!

**Comment by tfiers** [comment]
I see indeed that a pure toggle is not compatible with time-based switching.

When Time is Disabled however, a pure toggle does make sense I'd say.

**Comment by Spiritreader** [comment]
The swapping logic is still available in the program, but it would require the following things to be done
- Add another toggle hotkey
- Show/Hide different hotkey configurations depending on what mode is selected (when time switching is disable, the switch page should show the toggle hotkey, otherwise it shows the force hotkeys)
- Add an option to toggle the themes using the context menu (must update whenever the mode is switched)

The most important thing is that if this gets implemented, there is *zero* confusion about what the toggle hotkey does.
It must always be clear that it *only* works when time based switching is disabled.

The usability of the feature must be guaranteed beyond its correct functionality.

**Comment by tfiers** [comment]
That sounds excellent!

**Comment by tooomm** [comment]
> What is on the radar would be something like "force theme until next sunrise/sunset", but no details on this yet.

That's requested in https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/issues/439 btw 👍

**Comment by Spiritreader** [comment]
I've made progress on this, you should now be able to set WinKeys in the UI as hotkeys.

**Comment by Spiritreader** [comment]
No updates in a while, seems like the win hotkey is now working. Closing.
