### ISSUE TITLE
[Feature Request] Windows Terminal

### ISSUE THREAD

**Issue by Enf0** [AutoDarkMode/Windows-Auto-Night-Mode#427]
Would be great if AutoDarkMode could change the theme of [Windows Terminal](https://github.com/Microsoft/Terminal). It has been suggested in microsoft/terminal#4066 to be implemented directly, but there doesn't seem to be any official progress, so some users have resorted to custom Powershell scripts and scheduled tasks in the meantime. 

This is semi-related to #121, but for Windows Terminal instead of the built-in cmd/Powershell.

**Comment by Spiritreader** [comment]
I believe that, since there can be multiple profiles for different terminals, it makes more sense to use the ADM user script engine
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts
and just use the existing powershell scripts and let auto dark mode call them.

However, it looks like there's an update for this where WindowsTerminal supports adhering to the selected OS theme, which will make this redundant.

**Comment by Gravifer** [comment]
For those who are interested, maybe [this](https://gist.github.com/Gravifer/6511126e6c174c3ab7c647be43735dcc#file-z_adm_scripts-yaml) can serve as a dirty fix before @[Windows Terminal](https://github.com/microsoft/terminal/issues/4066) implements this.
