### ISSUE TITLE
Enable the 'Please Wait' screen whilst theme is switching?

### ISSUE THREAD

**Issue by My-Name-Is-Adam** [AutoDarkMode/Windows-Auto-Night-Mode#468]
I have setup a AHK script to change a regfile for T-Clock Redux and switch the theme by invoking the custom keyboard shortcut set in your application on pressing a different hockey. The regfile changes a value which ensures the clock changes colour when I switch themes automatically. 

I was having issues with the scripts hence why I just went about it this way instead. I'm not sure if it is because I am using a third party theme but changing app and windows light/dark and switching the theme is very slow. It takes around 10 seconds and explorer hangs whilst this is happening. 

I'd like for the Please Wait screen to appear as it does when we manually change the theme so that when I don't see windows and parts of the theme change bit by bit. It would be a lot cleaner this way. 

On doing some research I found tbis https://github.com/qwerty12/AutoHotkeyScripts/blob/master/SetThemeFrom

And this https://www.autohotkey.com/boards/viewtopic.php?p=91548&sid=9e6278fd3cede74a5f247eecd3006a25#p91548

I can see you used some of that code here: https://programtalk.com/vs4/csharp/AutoDarkMode/Windows-Auto-Night-Mode/AutoDarkModeSvc/Handlers/ThemeHandler.cs/?

I've not tried changing that code as not really sure what to change but I'm guessing based on the Autohotkey link above it would change the theme and display the please wait screen so I could essentially use just the script to accomplish this without your software but I'm no expert so I think using your software would be easier unless you need to change a lot on your end to accomplish this? 

I would appreciate any help. Thank you.

**Comment by Spiritreader** [comment]
There are currently no plans to introduce user-blocking overlays during the theme switch.

System switch performance is actually dependent on Windows (Auto Dark Mode uses the APIs found in Windows Control Panel to switch theme) and is indeed affected by the amount of explorer processes being opened.

There's nothing that can be done to improve switch performance as this is entirely dependent on Microsoft's implementation.
For example, on my desktop it takes around 5-10 seconds, but on my laptop it switches within 1-2 seconds without hitches.

Not quite sure why either, but I've noticed pretty huge differences in performance.
Best you can do is wait for 22H2 which is supposed to improve switching performance, but currently breaks explorer switch due to another MS bug with theme.cpl and explorer.
