### ISSUE TITLE
Add a label for offset setting?

### ISSUE THREAD

**Issue by kazerniel** [AutoDarkMode/Windows-Auto-Night-Mode#484]
Just realised that the offset number doesn't mean hours, but minutes. Maybe would be worth to add a quick line for new users to make this clear from the start?

**Comment by tooomm** [comment]
Definitely needed! 💯

**Comment by PtrStruct** [comment]
I'm working on this.

**Comment by tooomm** [comment]
I do not see this solved in 10.3.0.77 🤔 
No explanation of the offset setting for me yet.

**Comment by FunnyPocketBook** [comment]
No need to be so demanding and harsh about it, @tooomm. It's literally just a label, it's not a critical bug or something.
There are nicer ways to make them aware of this feature still being missing. Remember, they are doing this for free in their own free time - have you donated already?

**Comment by tooomm** [comment]
You strongly misread and misinterpreted my post. 😃 @FunnyPocketBook 

I simply pointed out that this ticket got probably closed by mistake. At least that's the natural assumption given the available information.

**Comment by Spiritreader** [comment]
I do agree with @FunnyPocketBook here tho.

There is no guarantee that fixes/enhancements/improvements that have been completed and implemented are immediately available to end users.
I also did move the issue back to "Done" and closed the issue, which means that it's solved, but not yet available to the public.

![image](https://user-images.githubusercontent.com/18438899/197341223-69b71fa8-3161-4707-b4bd-479a234e2f6f.png)

I was working on Mica support for Win11 and the added label for the offset text got pushed back a commit. The changes were thus temporarily only locally in my repo.
These sort of mistakes just happen sometimes, especially if you work on the project between other stuff that needs to get done.

Now, except for active core maintainers, there is no need to remind devs of open source software that work on a passion basis to push a commit or make a fix available. because you don't see 
- the exact commit referenced
- changes in the beta
less than 11 hours after an issue status has changed.

I do get an email and a notification for stuff like this, and so does everyone who subscribed to this topic. So I actually have to spend time reading through these messages instead of getting actual work done.
Yes, if you don't see changes after a few days it okay to ask nicely, but this instance is unwarranted.

There will be no further statement on this from my end, I'm busy with life & working on 10.3.
Thanks for reading.
