### ISSUE TITLE
Seems to break on Windows 11 22H2 Update

### ISSUE THREAD

**Issue by ToothyDev** [AutoDarkMode/Windows-Auto-Night-Mode#506]
### Description

It's really weird. Since I updated to 22H2, it just doesn't work anymore. My Windows always stays on the selected settings in the settings app, Auto Dark Mode doesn't change anything, only once right after you install it. Force Dark Mode doesn't work either
I'm obviously on the latest version of the program, and if you need any more info I'll provide it, I just assume its a weird W11 22H2 change

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9641816/service.log)
[config.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9641817/config.txt)

### Operating System

W11 22H2 22621.521

### Commit Hash and Version

5e6ea8a

EDIT: After changing the Windows settings randomly a dozen of times and changing the set time in ADM, it seems to work - even though ADM only turns dark / light halfway, the right side of the app doesn't change colors until you reopen it
After some more extensive testing it seems to mainly be window explorer that is unaffected by ADM, while it will happily go dark / light if changing the windows-setting for it, but never through ADM

**Comment by fh2ctm** [comment]
I have this issue as well. Moreover, the task bar font (date, time, etc.) does not automatically switch colors when the theme changes.

**Comment by ToothyDev** [comment]
> I have this issue as well. Moreover, the task bar font (date, time, etc.) does not automatically switch colors when the theme changes.

Same for the font colour of the toolbar in explorer. Microsoft messed up, but maybe ADM can fix it somehow given it works when changing the built in settings

**Comment by Spiritreader** [comment]
Nope we can't.

10.2 will release soon which addresses *most* of the issues, but we use the theme API, not the new built in settings API.
These APIs are private and require windows source code leaks (the one we currently use is from the Windows XP era)

**Comment by sppmasterspp** [comment]
- Commit: `f7a700b`
- Service: `10.2.0.18`
- Updater: `2.4.2`
- App: `10.0.1.0`
- Shell: `1.3.1.0`
- .Net: `6.0.7`
Windows 11 22H2
For me this version cannot auto switch to dark mode at the set time. It will auto switch to light mode though.

**Comment by otomad** [comment]
It seems that this affects the wrong colors in the taskbar and tray when switching in Windows 11 22H2.

When the computer wakes up after sleeping, it will return to normal.

**Comment by cyberpower678** [comment]
Same problem here too.  When it tries to switch, it instead makes Windows Explorer unusable.  Scrolling breaks, menus and icons flash, quick start flashes, and hovering over the open window tiles on Taskbar doesn't work either keeping my windows forcibly minimized when I have more than one of a program open.  Both auto dark mode and Explorer get pegged to 100% CPU.  Killing auto dark mode brings everything back to normal until the next time it tries to switch the theme.

**Comment by Spiritreader** [comment]
> Same problem here too. When it tries to switch, it instead makes Windows Explorer unusable. Scrolling breaks, menus and icons flash, quick start flashes, and hovering over the open window tiles on Taskbar doesn't work either keeping my windows forcibly minimized when I have more than one of a program open. Both auto dark mode and Explorer get pegged to 100% CPU. Killing auto dark mode brings everything back to normal until the next time it tries to switch the theme.

Please upload logs and config, but I assume two things are happening here

- a) you have Theme mode enabled
- b) you have "Restore themes when changed externally" enabled
- c) the logs say switch source "external"

Most likely you have an external influence trying to switch themes for you, and the "restore themes when changed externally" does exactly as it says, it re-applies as soon as it detects a change.
So if you have something that changes your wallpaper or anything other related to theming you get this behavior.

This is actually intended behavior. If you want it off, disable that setting.
If that's not the case and ADM is still doing it, then I *STILL* need logs because it doesn't help if you say you have a problem, but don't provide anything for us to look into.

**Comment by cyberpower678** [comment]
> > Same problem here too. When it tries to switch, it instead makes Windows Explorer unusable. Scrolling breaks, menus and icons flash, quick start flashes, and hovering over the open window tiles on Taskbar doesn't work either keeping my windows forcibly minimized when I have more than one of a program open. Both auto dark mode and Explorer get pegged to 100% CPU. Killing auto dark mode brings everything back to normal until the next time it tries to switch the theme.
> 
> Please upload logs and config, but I assume two things are happening here
> 
> * a) you have Theme mode enabled
> * b) you have "Restore themes when changed externally" enabled
> * c) the logs say switch source "external"
> 
> Most likely you have an external influence trying to switch themes for you, and the "restore themes when changed externally" does exactly as it says, it re-applies as soon as it detects a change. So if you have something that changes your wallpaper or anything other related to theming you get this behavior.
> 
> This is actually intended behavior. If you want it off, disable that setting. If that's not the case and ADM is still doing it, then I _STILL_ need logs because it doesn't help if you say you have a problem, but don't provide anything for us to look into.

The option was on, yes, but no, there is no external influence on the theme settings.  The only thing influencing themes is ADM.  Even with the option off, it was still happening when it came time to switch to dark mode.  
[data.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9747396/data.zip)

**Comment by Spiritreader** [comment]
Firstly, you are using an outdated version of Auto Dark Mode.

Secondly:
>  there is no external influence on the theme settings.

If the registry key is triggered, there most certainly is.
If you aren't running external programs, I assume that Microsoft changed something that causes updates to the registry key prematurely.
ADM with that setting enabled is reactive, not proactive. It can't switch the theme unless the registry key responsible for holding the theme path data is externally changed to something else than what it set.

> Even with the option off, it was still happening when it came time to switch to dark mode.

The only point in the code where an external theme switch event is produced is the monitor active theme handler. 
If it's off, it's no longer called.
What you were observing were mostly still-outstanding events that have been fired but not processed due to the sheer amount of them.

As a mitigation, I will rate-limit windows theme monitoring in a future beta build.
Make sure to switch to the beta channel and stay on the latest builds.

**Comment by cyberpower678** [comment]
Well then it’s reacting to something that Microsoft themselves changed.  The only application that I have installed that tampers with theme settings is ADM.  This could be an incompatibility with 22H2.  My theme doesn’t change with ADM off, nor does it change when I manually change it in Windows.  When I restart ADM with the enforcer enabled it will not repeatedly try to change the theme to itself over and over and over until it actively tries to change the theme to dark or light mode.  Then it gets stuck in a loop of setting it to itself over and over.As for the matter of being out of date, the application reports being on 10.2.0.18 with automatic updates enabled.  The application reports no new version is available.   I don’t see a newer version on GitHub at this time.On Oct 10, 2022, at 12:45, Sam ***@***.***> wrote:﻿
Firstly, you are using an outdated version of Auto Dark Mode.
Secondly:

there is no external influence on the theme settings.

If the registry key is triggered, there most certainly is.
If you aren't running external programs, I assume that Microsoft changed something that causes updates to the registry key prematurely.
ADM with that setting enabled is reactive, not proactive. It can't switch the theme unless the registry key responsible for holding the theme path data is externally changed to something else than what it set.

Even with the option off, it was still happening when it came time to switch to dark mode.

The only point in the code where an external theme switch event is produced is the monitor active theme handler.
If it's off, it's no longer called.
What you were observing were mostly still-outstanding events that have been fired but not processed due to the sheer amount of them.
As a mitigation, I will rate-limit windows theme monitoring in a future beta build.
Make sure to switch to the beta channel and stay on the latest builds.

**Comment by cyberpower678** [comment]
After doing some further testing you are right that disabling the box prevents subsequent auto-fires when the theme is already active.

When I enable the enforcer, everything is fine.  When it goes to change the theme, or when I change it, and ADM changes it back, it will change the theme successfully, but it gets itself stuck in a loop after that, constantly trying to set the already active them over and over.

When the enforcer is off it will change the theme normally and not get stuck in a loop.  From my observations, Microsoft is doing something with the registry keys as the themes are being switched, and ADM might be polling the keys too fast and thinking the theme is getting switched to something else.

**Comment by ZMYaro** [comment]
I assume this is the same issue(?)  Recently, when Auto Dark Mode changes my theme, it has been switching just the Windows mode, and not the app mode.  It also changes my wallpaper to solid black and my theme color to gray.  So far, it seems to stop happening when I disable ADM, so I am inclined to think it is ADM causing it, and not _only_ an issue in Windows, but I _am_ on the Windows and ADM beta channels.
[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/9749882/service.log)

**Comment by Spiritreader** [comment]
@ZMYaro This is a different issue entirely and has to do with theme synchronization.
Please enable the debug flag in the config.yaml file here
![image](https://user-images.githubusercontent.com/18438899/194972840-1e7b5047-a893-4683-9594-d75677e8ba3c.png)

Then exit the Auto Dark Mode service and restart it. Try switching themes again and post the logs

**Comment by ZMYaro** [comment]
@Spiritreader Sorry, my bad!  Filed as #547.

**Comment by Spiritreader** [comment]
10.3 should address all 22H2 issues as best as possible, for the rest please check out the list of known limitations:
https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Known-limitations
