### ISSUE TITLE
Update MS store app

### ISSUE THREAD

**Issue by albertopasqualetto** [AutoDarkMode/Windows-Auto-Night-Mode#538]
### Question
If i download the app through MS store, then I may get that there is an updated version from the embedded updater.
If i click on the relative notification, then it makes me download it from Github.
I think this is an inconsistency, shouldn't the app be updated from MS store if it is downloaded from there? Also aren't they 2 different packages? .appx and .exe?
Anyway what should I do in order to update the MS store app, wait?

**Comment by Spiritreader** [comment]
Our app has to go through Microsoft's checks before we publish them.

### Addressing the inconsistency

> I think this is an inconsistency, shouldn't the app be updated from MS store if it is downloaded from there? Also aren't they 2 different packages? .appx and .exe?

Since Microsoft requires unpackaged apps to handle updates on their own, our internal updater uses our preferred method of publishing the app, which is github (or our auto update system that also pulls from github).

We use unpackaged deployment.
There is no appx due to the amount of work required to switch the build process. So the .exe is the only installer file we offer.
Yes, this is an inconsistency, but mostly because Microsoft is making it difficult (similar to google play store / apple app store)

### How to use the auto updater

Also the update notification (and our internal updater) is capable of automatically updating without requiring you to download an executable.
This is true for the version you download from the MS store, and if you select the recommended install option on the installer.

When the notification appears, you can click on the "Update" button instead of the notification itself, which will perform the update automatically.
You can check for updates on the settings page if you miss the initial notification or dismiss it.

### When will the store executable be updated

10.2 in itself is a stable version, but it's not quite where we want it to be currently in terms of reliability.
As such, I think we may opt to publish 10.3 on the store.
I am not the one handling our store presence, that is @Armin2208. He can also probably shed some light when it's gonna be updated.

### How to use the updater gif
![updateprocess2](https://user-images.githubusercontent.com/18438899/194672379-872680c6-2933-4d33-b922-9d0dfc11a23c.gif)

**Comment by albertopasqualetto** [comment]
Thanks! I've been very exhaustive.
