### ISSUE TITLE
When language is set to Polish (pl), Dutch (nl) toast notifications appear

### ISSUE THREAD

**Issue by wojtekmaj** [AutoDarkMode/Windows-Auto-Night-Mode#630]
### Description

See screenshot

### Log Data

-

### Commit Hash, Version and Windows Build

- Commit: `679decc`
- Service/App: `10.3.1.11`
- Updater: `2.5.2`
- Shell: `1.3.1.0`
- .Net: `7.0.0`
- Windows: `22623.885`

### Screenshots / Videos

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/5426427/202921615-fd6c7aed-529d-49ed-b0df-520221d75a00.png">

**Comment by Spiritreader** [comment]
I can't reproduce this.

The service probably has the wrong locale set (most likely because it was changed in the app without the service being restarted cleanly)

I recommend checking your `config.yaml` file and ensure that the correct locale is set `UICulture = pl` and restart the service.

Since you didn't provide neither the log nor the config file so I am unable to look into this any further.
