### ISSUE TITLE
Auto switching doesn't work when user disconnected

### ISSUE THREAD

**Issue by svintuss** [AutoDarkMode/Windows-Auto-Night-Mode#698]
### Description

I use a Windows server with RDP. After upgrading from 10.1.0.10 to 10.0.3.90 auto switching works only when I'm connected. If toggle time comes and I'm disconnected interface stays the same until next toggle time. Happens both with coordinates or custom times. 
In some cases instead of complete theme switch only taskbar switches modes and windows color stays the same.

### Log Data

[service_config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/11076935/Archive.zip)

### Commit Hash, Version and Windows Build

- Commit: `212dbb4`
- Service/App: `10.3.0.90`
- Updater: `2.5.2`
- Shell: `1.3.1.0`
- .Net: `6.0.10`
- Windows: `20348.1487`

**Comment by Spiritreader** [comment]
What do you mean by connected? You mean RDP?
If you refer to RDP you have to disable this setting (turn it off, remove the checkbox)
![image](https://user-images.githubusercontent.com/18438899/228030798-492a0575-5964-4797-bca7-72f619e1af19.png)

**Comment by svintuss** [comment]
@Spiritreader thank you. It worked. 

Although this checkbox is somehow misleading and counter-intuitive.

**Comment by Spiritreader** [comment]
> @Spiritreader thank you. It worked.
> 
> Although this checkbox is somehow misleading and counter-intuitive.

Whats counter intuitive is that there's a bug in Windows 10 that causes lock screen theme switching to fail under certain circumstances. In Win11, this functionality has been entirely removed by MS. 

Most users don't run into this issue as they are neither multi accounting nor using RDP.
Allowing theme switches during lock screen helps circumvents the lag that happens during a theme switch on Windows, however we have found more scenarios where this is incompatible as of late.

The checkbox does exactly what it's claims and intuition is an entirely subjective matter in UX Design.

However we do plan of having that setting off-by-default in the future such that new users have the ability to turn it on if they are able to profit from lock screen theme switches.

**Comment by svintuss** [comment]
I didn't mean to offend in any way. Just pointed out that this checkbox although fixes the issue doesn't give a clue about its effects on RDP setup.

I mentioned that everything worked fine with 10.1.0.10. I can't remember wether that version had this lockscreen checkbox or not, but I didn't change anything - just updated the app and suddenly switching stopped working.

**Comment by Spiritreader** [comment]
> I didn't mean to offend in any way. Just pointed out that this checkbox although fixes the issue doesn't give a clue about its effects on RDP setup.

No offense taken, just wanted to point out that intuition is different for everyone since that's what my UX/UI professors hammered into our brains for a year.

The checkbox isn't meant to fix RDP specifically. 
It rather fixes problems for *any* scenario where the user session is inactive or uninitalized, RDP being one of them.

It worked fine with 10.1.0.10 because this version used a different code base for theme switching (registry key based), which was removed in Win11. 
Currently it seems like the IThemeManager2 API set requires an active user session to work properly.
All Windows builds greater than 19044 use the Microsoft IThemeManager2 API starting with 10.3.
The reason is that maintaining two complete sets of theme switching methods is infeasible to maintain, and we wanted to include the more recent Win10 builds in new feature rollouts wherever possible.
