### ISSUE TITLE
Dark font in the tray

### ISSUE THREAD

**Issue by Detsle** [AutoDarkMode/Windows-Auto-Night-Mode#743]
### Description

A light theme is installed, but the clock, wi-fi, battery, other is not visible in black against the wallpaper background.
How to make the clock white with a light theme?

### Log Data

[service.log](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/11936408/service.log)
[config.zip](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/11936417/config.zip)

### Commit Hash, Version and Windows Build

Windows 10 22H2 (19045.3155)

### Screenshots / Videos

![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/22348086/8a60015b-92d3-4790-8d7c-feac06f411b9)

**Comment by Spiritreader** [comment]
Hey!

I'm unsure how we are able to help here because what you're describing is normal Windows behavior.
If you set the system color theme to light, the taskbar will change its icons to black.

> How to make the clock white with a light theme?

The answer to that is: You can't. The only way to have the taskbar show white tray icons is by setting the System theme to always dark. However, then the start menu will also retain its dark mode

**Comment by Detsle** [comment]
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/22348086/143d2e9c-aa03-4e44-b609-196bc22c6227)
Why then choosing a Windows theme (not light, but regular), the font becomes white, although it is not a dark theme?

**Comment by Spiritreader** [comment]
> ![image](https://user-images.githubusercontent.com/22348086/253593861-143d2e9c-aa03-4e44-b609-196bc22c6227.png) Why then choosing a Windows theme (not light, but regular), the font becomes white, although it is not a dark theme?

Regular uses the "dark" system setting

**Comment by Detsle** [comment]
Why then, in the 1.0 version of the application, the font in the tray always remains white?

**Comment by Detsle** [comment]
Is there any way I can do the same, only in the latest version of your application?

**Comment by Spiritreader** [comment]
> Is there any way I can do the same, only in the latest version of your application?

Yes, I outlined this above:

The answer to that is: You can't. The only way to have the taskbar show white tray icons is by setting the System theme to always dark. However, then the start menu will also retain its dark mode
![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/18438899/cd5811e5-5341-4a3d-9105-655b7eda5f05)


> Why then, in the 1.0 version of the application, the font in the tray always remains white?

Because when 1.0 was released (which was way before I joined the project) Windows did not even have split options yet for System and Apps theme.

**Comment by Detsle** [comment]
> > ![image](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/assets/22348086/2acfd8ac-79bf-4848-972c-4887a40a119d)
Thank you, it helped me 👍
