### ISSUE TITLE
Great app but boot load is high

### ISSUE THREAD

**Issue by Artaherzadeh** [AutoDarkMode/Windows-Auto-Night-Mode#838]
Hi
There is no need for the app to be running all the time, is there?
It can be updated every week to get new sunrise and sunset times and just set a task scheduler task for turn off and on.
Right now, it's one of the few apps that high impact on my startup and does a very simple thing which is only changing the Windows theme.

**Comment by Armin2208** [comment]
We intentionally chose an always running background process. We will no longer be making structural changes to Auto Dark Mode. Older versions were based on the task scheduler principle, but this limited our abilities, That's why we switched. You can trust us that Auto Dark Mode has minimal impact on your Computer performance and batter ylife.

**Comment by Spiritreader** [comment]
> it's one of the few apps that high impact on my startup 

That is because we are shipping the .NET runtime.
There is framework-dependent deployment, but that means that users have to install the latest net runtime in order for ADM to work.

This is the case with all applications that are self-contained.
