### ISSUE TITLE
Auto adjust Windows display brightness

### ISSUE THREAD

**Issue by udobehm** [AutoDarkMode/Windows-Auto-Night-Mode#84]
Hi Armin,

can you add the feature to also auto adjust the display brightness of Windows that normally can be changed (manually) in the Windows Info Center?
Would like it to be changed too when the night mode becomes turned off or on with the help of your app by two possible options: Either increase and the decrease the brightness relative to the current set value in Windows (e. g. by +/- 10...15...20 or something) or set it to absulute values (e. g. 70 during day and 50 during night).

Think you could add this to your app?

**Comment by Spiritreader** [comment]
This should definitely be possible to implement in version 3.

I've researched how complex it would be to implement by using [Monitorian](https://github.com/emoacht/Monitorian) as a reference.

It is certainly possible to use [WMI](https://docs.microsoft.com/en-us/windows/win32/wmicoreprov/wmisetbrightness-method-in-class-wmimonitorbrightnessmethods) in order to change screen brightness quickly and easliy. 
However multiple aspects need to be considered to in order to guarantee a bug and unwanted side effect free experience for everyone.

- DDC/CI handling for non built in screens
- Handling Multiple Monitor Instances correctly
- Handling of adaptive system brightness (power management)

Ideally we should use the MonitorManager found in Monitorian.Core as a reimplementation would be a substantial amount of work and will introduce unnecessary delays and bugs.
It is pretty feature complete and should work quite nicely. Using the new module infrastructure we can control this instance independently, isolated from other logic which is desireable.

That being said this is defintely a cool feature that has been toyed with since the Inception of v3.
It would however also require AutoDarkMode to declare an MIT license.

**Comment by maboroshin** [comment]
This feature can be found in the following software: [twinkle-tray on GitHub](https://github.com/xanderfrangos/twinkle-tray/releases)

**Comment by udobehm** [comment]
Thanks. Unfortunately, the app doesn't allow to switch according to sunrise and sunset information...

**Comment by udobehm** [comment]
Do you know any other app that can do this (changing brightness according to sunrise/sunset information or Windows theme change??

**Comment by udobehm** [comment]
Or can you integrate this feature in your app??

**Comment by udobehm** [comment]
Could this help to implement the function in your app, also with sunrise and sunset information? https://askubuntu.com/questions/894460/automatically-adjust-display-brightness-based-on-sunrise-and-sunset

**Comment by udobehm** [comment]
Hey Armin, did you think about implementing this functionality? Your app would be best for this I think because it already looks for sunset and sunrise information what Twinke Tray unfortunately doesn't... Would be great if you could implemet this feature! Thx!

**Comment by Dylan96** [comment]
If you could adjust the monitor brightness like this software [Win10_BrightnessSlider](https://github.com/blackholeearth/Win10_BrightnessSlider)  it would be awesome

**Comment by stefnotch** [comment]
https://github.com/emoacht/Monitorian is another program which can adjust the monitor brightness. It's really well made, the only catch is that it's really not designed to be used as a library.

**Comment by Armin2208** [comment]
Twinkle Tray also have a command line interface, so you could make your own script

**Comment by Spiritreader** [comment]
> Twinkle Tray also have a command line interface, so you could make your own script

I think this is our accepted solution for now. Please use the ADM scripting engine https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/How-to-add-custom-scripts to interface with tools such as twinkle-tray.

Brightness adjustment is, especially given the recent developments with Win11, out of scope and there are a lot of tools that already cover this.

Thanks nonetheless!
