### ISSUE TITLE
When switching theme, the taskbar becomes invisible

### ISSUE THREAD

**Issue by unalignedcoder** [AutoDarkMode/Windows-Auto-Night-Mode#841]
### Description

**Important**: The taskbar is AT THE TOP

Since installing this beta version of ADM, when I switch the theme, **the taskbar becomes invisible beyond the border of the screen**.

The only workaround is to briefly change screen resolution and revert the change.

### Log Data

[config.yaml.txt](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/files/15088143/config.yaml.txt)
[Uploading service.log.txt…]()

### Commit Hash, Version and Windows Build

Windows 10 22H2 19045.4291
ADM version 10.4.2.15

**Comment by unalignedcoder** [comment]
Never mind. It seems the problem goes away when checking the "Always refresh DWM" setting.

**Comment by Spiritreader** [comment]
Intuitively, that sounds like there's a problem with your StuckRects3 definitions and less like an issue with ADM.
We only use Windows APIs and have no control over the actual theme switch itself. That is handled by Windows entirely.

`Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3`

I can not reproduce this issue with my win10 test build, with any taskbar position.

Since it's working with DWM refresh (DWM is instructed to rebuild everything from scratch), which is specifically intended to give Windows another nudge as in "do it right this time", I would label this as Windows issue.

**Comment by unalignedcoder** [comment]
Well, this only happens when ADM is involved. 
The taskbar disappears behind the top edge of the screen, and only a pixel or so remains visible.
I agree something might have changed in Windows that is interfering with ADM.
I only noticed this because I inadvertently unchecked "Always refresh DWM", the problem was likely always there.
I don't think it's a taskbar positioning issue, something with resolution, perhaps.
