### ISSUE TITLE
Switch out of battery saver temporarily when switching modes. 

### ISSUE THREAD

**Issue by JesFEREM** [AutoDarkMode/Windows-Auto-Night-Mode#98]
**Describe the bug**
I feel that the problem with switching between dark and light themes when in battery saver could be easily fixed by adding a task to automatically turn off battery saver, switch themes, and then turn battery saver back on very quickly. 

**Expected behavior**
Battery Saver is temporarily disabled long enough to properly switch themes. 

**Environment:**
 - OS Version: Windows 1909
 - Night-Mode Version 2.3.1 (Installed via Chocolatey)
 - Language: English

**Comment by Armin2208** [comment]
Problem: Windows doesn't allow switching the battery saver mode on or off.
The only workaround would be to reduce the activation percentage for battery saver to 0% in the current power scheme. But this not resolves the issue for people who manually activated it for the purpose of a longer battery life at certain days.
This is why I skip this issue for now for version 3.0.

Anyways this issue is only relevant because Microsoft didn't fixed the theme switch bug in version 2004. If Windows would support a flawless theme switch in battery saver mode, this feature wouldn't be needed.

**Comment by Spiritreader** [comment]
I might have discovered a way to achieve this.

The battery saver activation percentage slider is maybe configurabel via powercfg, making it possible after all. Will need to investigate

https://docs.microsoft.com/en-us/windows-hardware/customize/power-settings/energy-saver-settings

**Comment by Spiritreader** [comment]
implemented in 129fc51

However this comes with a few limitations:

- Only works for battery powered devices
- You **have** to set the default battery percentage for enabling battery saver within the Auto Dark Mode settings, because there's no easy way to read this value.
